spring:
  application:
    name: user-management
  datasource:
    url: jdbc:mysql://localhost:3306/UserManagement?createDatabaseIfNotExist=true
    username: root
    password: Sumit@1020
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

rsa:
  public-key: classpath:certs/public.pem
  private-key: classpath:certs/private.pem

server:
  port: 8081

